- .gitignore
- dockerfile/Dockerfile
- dockerfile/README.md
- dockerfile/build.sh
- dockerfile/common/LICENSE
- dockerfile/common/README.md
- dockerfile/common/provision/README.md
- dockerfile/common/provision/default/image-config.sh
- dockerfile/common/provision/default/image-prep.sh
- dockerfile/common/provision/puppet/image-config.sh
- dockerfile/common/provision/puppet/image-prep.sh
- dockerfile/common/scripts/base.sh
- dockerfile/common/scripts/docker-build.sh
- dockerfile/common/scripts/docker-push.sh
- dockerfile/common/scripts/docker-run.sh
- dockerfile/common/scripts/docker-stop.sh
- dockerfile/common/scripts/entrypoint.sh
- dockerfile/common/wso2base/Dockerfile
- dockerfile/common/wso2base/README.md
- dockerfile/common/wso2base/build.sh
- dockerfile/package.xml
- dockerfile/pom.xml
- dockerfile/push.sh
- dockerfile/run.sh
- dockerfile/stop.sh
This commit include Dockerfile and necessary script to build docker image based on the default or Puppet provisioning
> add dockerfile for wso2ei-6.1.1

- docker-compose/integrator-analytics/docker-compose.yml
- docker-compose/integrator-broker-analytics/README.md
- docker-compose/integrator-broker-bps-analytics/README.md
- dockerfiles/analytics/Dockerfile
Updates to READMEs and Dockerfiles.
[1] - Add few port exports to Analytics dockerfile
[2] - Add secure-vault lib addition to broker connection READMEs.
> Updates to READMEs and Dockerfiles

- dockerfiles/README.md
- dockerfiles/base/Dockerfile
Add dockerfile logic to reduce image size and add user/group ID
> Add dockerfile logic to reduce image size and add user/group ID

- dockerfiles/README.md
Update README with docker version to use
> Update README with docker version to use

- dockerfiles/README.md
- dockerfiles/base/Dockerfile
Update dockerfile README instructions
> Update dockerfile README instructions

- docker-compose/integrator-analytics/docker-compose.yml
- docker-compose/integrator-broker-analytics/docker-compose.yml
- docker-compose/integrator-broker-bps-analytics/docker-compose.yml
> Adding the private Docker registry. Issue #30
> Adding private Docker registry domain

- docker-compose/integrator-analytics/README.md
- docker-compose/integrator-analytics/docker-compose.yml
- docker-compose/integrator-broker-analytics/README.md
- docker-compose/integrator-broker-analytics/docker-compose.yml
- docker-compose/integrator-broker-bps-analytics/README.md
- docker-compose/integrator-broker-bps-analytics/docker-compose.yml
- dockerfiles/README.md
- dockerfiles/base/Dockerfile
- dockerfiles/integrator/Dockerfile
> fixes #32 
Adding MySQL connector jar and other required jars for the communication between Integrator and Message Broker via the Dockerfile. Mounting these jar from the Docker-compose is removed.
> Add libs via Dockerfile

- docker-compose/integrator-analytics/README.md
- docker-compose/integrator-broker-analytics/README.md
- docker-compose/integrator-broker-bps-analytics/README.md
fixes #34 
> Update the Docker compose Read me file.
> updates docker-compose readme

- dockerfiles/README.md
- dockerfiles/base/Dockerfile
- dockerfiles/integrator/Dockerfile
> Update README & dockerfiles

- docker-compose/integrator-analytics/README.md
> Update compose READMEs

- dockerfiles/base/Dockerfile
- dockerfiles/integrator/init.sh
> Push WSO2 Enterprise Integrator 6.2.x Docker resources to master - 24/05/2018.
> Merge 6.2.x branch to master branch

- docker-compose/integrator-bps-analytics/business-process/bin/wso2server.sh
- docker-compose/integrator-bps-analytics/business-process/conf/carbon.xml
- docker-compose/integrator-broker-bps-analytics/business-process/bin/wso2server.sh
- dockerfiles/broker/Dockerfile
- dockerfiles/broker/init.sh
- dockerfiles/business-process/Dockerfile
- dockerfiles/business-process/init.sh
- dockerfiles/integrator/Dockerfile
- dockerfiles/integrator/init.sh
> Prepare message broker profile Docker image for product clustering and artifact sharing during clustering. This closes https://github.com/wso2/docker-ei/issues/68 and fixes https://github.com/wso2/docker-ei/issues/70.
> Prepare message broker profile Docker image for product clustering and artifact sharing during clustering.
>  Prepare message broker profile Docker image for clustering

- docker-compose/integrator-analytics/README.md
- docker-compose/integrator-analytics/docker-compose.yml
- docker-compose/integrator-analytics/integrator/conf/axis2/axis2.xml
- docker-compose/integrator-analytics/integrator/conf/carbon.xml
- docker-compose/integrator-bps-analytics/README.md
- docker-compose/integrator-bps-analytics/business-process/conf/carbon.xml
- docker-compose/integrator-bps-analytics/docker-compose.yml
- docker-compose/integrator-bps-analytics/integrator/conf/axis2/axis2.xml
- docker-compose/integrator-broker-analytics/README.md
- docker-compose/integrator-broker-analytics/docker-compose.yml
- docker-compose/integrator-broker-analytics/integrator/conf/axis2/axis2.xml
- docker-compose/integrator-broker-analytics/integrator/conf/carbon.xml
- docker-compose/integrator-broker-bps-analytics/README.md
- docker-compose/integrator-broker-bps-analytics/business-process/conf/carbon.xml
- docker-compose/integrator-broker-bps-analytics/docker-compose.yml
- docker-compose/integrator-broker-bps-analytics/integrator/conf/axis2/axis2.xml
- docker-compose/integrator-broker-bps-analytics/integrator/conf/carbon.xml
- dockerfiles/README.md
- dockerfiles/analytics/Dockerfile
- dockerfiles/base/Dockerfile
- dockerfiles/broker/Dockerfile
- dockerfiles/business-process/Dockerfile
- dockerfiles/integrator/Dockerfile
- dockerfiles/msf4j/Dockerfile
#Purpose 
Add configuration files and resources for EI-6.3.0
> Add config files for EI 6.3.0

- dockerfiles/analytics/Dockerfile
- dockerfiles/analytics/init.sh
- dockerfiles/broker/Dockerfile
- dockerfiles/broker/init.sh
- dockerfiles/business-process/Dockerfile
- dockerfiles/business-process/init.sh
- dockerfiles/integrator/Dockerfile
- dockerfiles/integrator/init.sh
> Refine WSO2 Enterprise Integrator version 6.2.x Docker resources.
> Refine WSO2 Enterprise Integrator version 6.2.x Docker resources.
> Refine WSO2 Enterprise Integrator version 6.2.x Docker resources

- CHANGELOG.md
- README.md
- docker-compose/integrator-analytics/scripts/README.md
- docker-compose/integrator-bps-analytics/scripts/README.md
- docker-compose/integrator-broker-analytics/scripts/README.md
- docker-compose/integrator-broker-bps-analytics/scripts/README.md
> Fix README documentation and finalize the change log.
> Fix README documentation and finalize the change log
> Fix README documentation

- dockerfiles/alpine/analytics/dashboard/Dockerfile
- dockerfiles/alpine/analytics/worker/Dockerfile
- dockerfiles/alpine/broker/Dockerfile
- dockerfiles/alpine/business-process/Dockerfile
- dockerfiles/alpine/integrator/Dockerfile
- dockerfiles/alpine/msf4j/Dockerfile
- dockerfiles/centos/analytics/dashboard/Dockerfile
- dockerfiles/centos/analytics/worker/Dockerfile
- dockerfiles/centos/broker/Dockerfile
- dockerfiles/centos/business-process/Dockerfile
- dockerfiles/centos/integrator/Dockerfile
- dockerfiles/centos/msf4j/Dockerfile
- dockerfiles/ubuntu/analytics/dashboard/Dockerfile
- dockerfiles/ubuntu/analytics/worker/Dockerfile
- dockerfiles/ubuntu/broker/Dockerfile
- dockerfiles/ubuntu/business-process/Dockerfile
- dockerfiles/ubuntu/integrator/Dockerfile
- dockerfiles/ubuntu/msf4j/Dockerfile
> Use WSO2 product pack downloadable links to binaries available at JFrog Bintray. This fixes https://github.com/wso2/docker-ei/issues/140.
> Use WSO2 product pack downloadable links to binaries available at JFrog Bintray
> Use WSO2 product pack downloadable links to binaries available at JFrog Bintray

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- dockerfiles/alpine/analytics/dashboard/Dockerfile
- dockerfiles/alpine/analytics/worker/Dockerfile
- dockerfiles/alpine/broker/Dockerfile
- dockerfiles/alpine/business-process/Dockerfile
- dockerfiles/alpine/integrator/Dockerfile
- dockerfiles/alpine/msf4j/Dockerfile
- dockerfiles/centos/analytics/dashboard/Dockerfile
- dockerfiles/centos/analytics/worker/Dockerfile
- dockerfiles/centos/broker/Dockerfile
- dockerfiles/centos/business-process/Dockerfile
- dockerfiles/centos/integrator/Dockerfile
- dockerfiles/centos/msf4j/Dockerfile
- dockerfiles/ubuntu/analytics/dashboard/Dockerfile
- dockerfiles/ubuntu/analytics/worker/Dockerfile
- dockerfiles/ubuntu/broker/Dockerfile
- dockerfiles/ubuntu/business-process/Dockerfile
- dockerfiles/ubuntu/integrator/Dockerfile
- dockerfiles/ubuntu/msf4j/Dockerfile
> Merge 6.5.x branch with master branch - 2019-08-28.
> Merge 6.5.x branch with master branch
> Merge 6.5.x branch with master branch - 2019-08-28

- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/centos/streaming-integrator/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
- Update MySQL connector version for Streaming Integrator images
> Update MySQL connector version for Streaming Integrator images

- CHANGELOG.md
- Add release date in changelog
> Add release date in changelog

- CHANGELOG.md
- dockerfiles/alpine/analytics/dashboard/Dockerfile
- dockerfiles/alpine/analytics/worker/Dockerfile
- dockerfiles/alpine/broker/Dockerfile
- dockerfiles/alpine/business-process/Dockerfile
- dockerfiles/alpine/integrator/Dockerfile
- dockerfiles/alpine/msf4j/Dockerfile
- dockerfiles/centos/analytics/dashboard/Dockerfile
- dockerfiles/centos/analytics/worker/Dockerfile
- dockerfiles/centos/broker/Dockerfile
- dockerfiles/centos/business-process/Dockerfile
- dockerfiles/centos/integrator/Dockerfile
- dockerfiles/centos/msf4j/Dockerfile
- dockerfiles/ubuntu/analytics/dashboard/Dockerfile
- dockerfiles/ubuntu/analytics/worker/Dockerfile
- dockerfiles/ubuntu/broker/Dockerfile
- dockerfiles/ubuntu/business-process/Dockerfile
- dockerfiles/ubuntu/integrator/Dockerfile
- dockerfiles/ubuntu/msf4j/Dockerfile
> Change the remote location for downloading the MySQL connector jar.
Fix for #173
> Fix MySQL connector jar Download URL [6.5.x]

- CHANGELOG.md
- dockerfiles/alpine/analytics/dashboard/Dockerfile
- dockerfiles/alpine/analytics/worker/Dockerfile
- dockerfiles/alpine/broker/Dockerfile
- dockerfiles/alpine/business-process/Dockerfile
- dockerfiles/alpine/integrator/Dockerfile
- dockerfiles/centos/analytics/dashboard/Dockerfile
- dockerfiles/centos/analytics/worker/Dockerfile
- dockerfiles/centos/broker/Dockerfile
- dockerfiles/centos/business-process/Dockerfile
- dockerfiles/centos/integrator/Dockerfile
- dockerfiles/ubuntu/analytics/dashboard/Dockerfile
- dockerfiles/ubuntu/analytics/worker/Dockerfile
- dockerfiles/ubuntu/broker/Dockerfile
- dockerfiles/ubuntu/business-process/Dockerfile
- dockerfiles/ubuntu/integrator/Dockerfile
> Change the remote location for downloading the MySQL connector jar.
Fix for #172
> Fix MySQL connector jar Download URL [6.6.x]

- CHANGELOG.md
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/centos/micro-integrator/Dockerfile
- dockerfiles/centos/streaming-integrator/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
> Change the remote location for downloading the MySQL connector jar.
Fix for #168
> Fix MySQL connector jar Download URL [7.0.x]

- CHANGELOG.md
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/centos/micro-integrator/Dockerfile
- dockerfiles/centos/streaming-integrator/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
>Merge 7.0.x branch to the master branch
>Merge the latest release to the master branch.
> 7.0.x branch to the master branch

- CHANGELOG.md
- README.md
> Update change log documentation.
> Update change log documentation
> [6.6.x] Update change log documentation

- CHANGELOG.md
- README.md
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/centos/micro-integrator/Dockerfile
- dockerfiles/centos/streaming-integrator/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
Fix: 
https://github.com/wso2/docker-ei/issues/182
https://github.com/wso2/docker-ei/issues/181
> Change AdoptOpenJDK version 8 to 11 & update changelog

- CHANGELOG.md
- README.md
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/centos/micro-integrator/Dockerfile
- dockerfiles/centos/streaming-integrator/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
Merge v7.0.0.3 release into master - 2020/07/03
> Merge v7.0.0.3 release into master

- CHANGELOG.md
- README.md
- dockerfiles/alpine/analytics-dashboard/Dockerfile
- dockerfiles/alpine/analytics-dashboard/README.md
- dockerfiles/alpine/analytics-dashboard/docker-entrypoint.sh
- dockerfiles/centos/analytics-dashboard/Dockerfile
- dockerfiles/centos/analytics-dashboard/README.md
- dockerfiles/centos/analytics-dashboard/docker-entrypoint.sh
- dockerfiles/ubuntu/analytics-dashboard/Dockerfile
- dockerfiles/ubuntu/analytics-dashboard/README.md
- dockerfiles/ubuntu/analytics-dashboard/docker-entrypoint.sh
> This PR introduces Docker resources for WSO2 Analytics Dashboard version `1.0.0`. This closes #193 .  
> Introduces Docker resources for WSO2 Analytics Dashboard version `1.0.0`
> [7.1.0] Introduce Docker resources for Analytics dashboard 1.0.0

- CHANGELOG.md
- README.md
- dockerfiles/alpine/monitoring-dashboard/Dockerfile
- dockerfiles/alpine/monitoring-dashboard/README.md
- dockerfiles/alpine/monitoring-dashboard/docker-entrypoint.sh
- dockerfiles/centos/monitoring-dashboard/Dockerfile
- dockerfiles/centos/monitoring-dashboard/README.md
- dockerfiles/centos/monitoring-dashboard/docker-entrypoint.sh
- dockerfiles/ubuntu/monitoring-dashboard/Dockerfile
- dockerfiles/ubuntu/monitoring-dashboard/README.md
- dockerfiles/ubuntu/monitoring-dashboard/docker-entrypoint.sh
> This PR introduces Docker resources for WSO2 MI Monitoring Dashboard version `1.2.0`. This closes #195  .  
> Introduces Docker resources for WSO2 MI Monitoring Dashboard version `1.2.0`
> [7.1.0] Introduce Docker resources for WSO2 MI Monitoring Dashboard 1.2.0

- CHANGELOG.md
> This PR fixes #201 
> Fix incorrect changelog entries
> Fix incorrect changelog entries

- CHANGELOG.md
> [7.1.0] Merge 7.1.x branch into Master branch - 2020-08-18

- CHANGELOG.md
- README.md
> [7.1.0] Prepare the repository for the release v7.1.0.2

- CHANGELOG.md
- README.md
- dockerfiles/alpine/analytics-dashboard/Dockerfile
- dockerfiles/alpine/analytics-dashboard/docker-entrypoint.sh
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/micro-integrator/docker-entrypoint.sh
- dockerfiles/alpine/monitoring-dashboard/Dockerfile
- dockerfiles/alpine/monitoring-dashboard/docker-entrypoint.sh
- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/centos/analytics-dashboard/Dockerfile
- dockerfiles/centos/micro-integrator/Dockerfile
- dockerfiles/centos/monitoring-dashboard/Dockerfile
- dockerfiles/centos/streaming-integrator/Dockerfile
- dockerfiles/ubuntu/analytics-dashboard/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/monitoring-dashboard/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
> Merge 7.1.x branch into master branch - 2020-10-09. This PR fixes #234.
> [7.1.0] Merge 7.1.x branch into master branch - 2020-10-09

- CHANGELOG.md
> Update CHANGELOG for the latest release
> Create release for docker-ei 6.5.0.5
> [6.5.0] Update CHANGELOG for the latest release(6.5.0.5)

- CHANGELOG.md
> Update CHANGELOG for the latest release
> Create release for docker-ei 7.0.0.4
> [7.0.0] Update CHANGELOG for the latest release(7.0.0.4)

- CHANGELOG.md
> Update CHANGELOG for the latest release
> Create release for docker-ei 6.3.0.2
> [6.3.0] Update CHANGELOG for the latest release(6.3.0.2)

- CHANGELOG.md
> Add CHANGELOG
> Create release for docker-ei 6.2.0
> [6.2.0] Add CHANGELOG file

- dockerfiles/alpine/analytics-dashboard/Dockerfile
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/monitoring-dashboard/Dockerfile
- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/centos/analytics-dashboard/Dockerfile
- dockerfiles/centos/micro-integrator/Dockerfile
- dockerfiles/centos/monitoring-dashboard/Dockerfile
- dockerfiles/centos/streaming-integrator/Dockerfile
- dockerfiles/ubuntu/analytics-dashboard/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/monitoring-dashboard/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
Upgrade base OS images.
Git issue: https://github.com/wso2/docker-ei/issues/252
> Upgrade base OS images

- CHANGELOG.md
- dockerfiles/alpine/analytics-dashboard/Dockerfile
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/monitoring-dashboard/Dockerfile
- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/centos/analytics-dashboard/Dockerfile
- dockerfiles/centos/micro-integrator/Dockerfile
- dockerfiles/centos/monitoring-dashboard/Dockerfile
- dockerfiles/centos/streaming-integrator/Dockerfile
- dockerfiles/ubuntu/analytics-dashboard/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/monitoring-dashboard/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
Prepare Dockerfiles and changelog for the 7.1.0.3 release
> Prepare Dockerfiles and changelog for the 7.1.0.3 release

- CHANGELOG.md
- README.md
- dockerfiles/alpine/analytics-dashboard/Dockerfile
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/monitoring-dashboard/Dockerfile
- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/centos/analytics-dashboard/Dockerfile
- dockerfiles/centos/micro-integrator/Dockerfile
- dockerfiles/centos/monitoring-dashboard/Dockerfile
- dockerfiles/centos/streaming-integrator/Dockerfile
- dockerfiles/ubuntu/analytics-dashboard/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/monitoring-dashboard/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
Prepare for the 7.1.0.3 release
> Prepare for the 7.1.0.3 release

- CHANGELOG.md
> [6.6.0] Update the release date
> Create a new release
> [6.6.0]Update the release date

- CHANGELOG.md
> [6.5.0] Update the release date
> Create a new release
> [6.5.0]Update the release date

- CHANGELOG.md
> [6.3.0] Update the release date
> Create a new release
> [6.3.0]Update the release date

- CHANGELOG.md
> [6.2.0] Update the release date
> Create a new release
> [6.2.0]Update the release date

- CHANGELOG.md
> [6.4.0] Update changelog to reflect EI-6.4.0 release

- CHANGELOG.md
- dockerfiles/alpine/analytics/dashboard/Dockerfile
- dockerfiles/alpine/analytics/worker/Dockerfile
- dockerfiles/alpine/broker/Dockerfile
- dockerfiles/alpine/business-process/Dockerfile
- dockerfiles/alpine/integrator/Dockerfile
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/msf4j/Dockerfile
- dockerfiles/centos/analytics/dashboard/Dockerfile
- dockerfiles/centos/analytics/worker/Dockerfile
- dockerfiles/centos/broker/Dockerfile
- dockerfiles/centos/business-process/Dockerfile
- dockerfiles/centos/integrator/Dockerfile
- dockerfiles/centos/micro-integrator/Dockerfile
- dockerfiles/centos/msf4j/Dockerfile
- dockerfiles/ubuntu/analytics/dashboard/Dockerfile
- dockerfiles/ubuntu/analytics/worker/Dockerfile
- dockerfiles/ubuntu/broker/Dockerfile
- dockerfiles/ubuntu/business-process/Dockerfile
- dockerfiles/ubuntu/integrator/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/msf4j/Dockerfile
This PR updates the Kubernetes membership scheme jar's url
> [6.4.0] Update kubernetes membership scheme jar's url

- dockerfiles/ubuntu/msf4j/Dockerfile
This PR removes redundant code in msf4j Dockerfile
> [6.4.x] Remove redundant part in msf4j Dockerfile

- CHANGELOG.md
> Update changelog for EI v6.4.0.5 release

- CHANGELOG.md
- dockerfiles/alpine/analytics-dashboard/Dockerfile
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/monitoring-dashboard/Dockerfile
- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/centos/analytics-dashboard/Dockerfile
- dockerfiles/centos/micro-integrator/Dockerfile
- dockerfiles/centos/monitoring-dashboard/Dockerfile
- dockerfiles/centos/streaming-integrator/Dockerfile
- dockerfiles/ubuntu/analytics-dashboard/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/monitoring-dashboard/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
> Add the missing 7.1.0.4 release for the master
> Prepare the Dockerfiles for the 7.1.0.4 release

- CHANGELOG.md
> update changelog file

- dockerfiles/ubuntu/monitoring-dashboard/Dockerfile
> [MI-Dashboard] Add OpenJDK11U-jdk_x64_linux_hotspot_11.0.13_8.tar.gz to the Ubuntu

- dockerfiles/ubuntu/micro-integrator/Dockerfile
> Add OpenJDK11U-jdk_x64_linux_hotspot_11.0.13_8.tar.gz to the Ubuntu

- dockerfiles/ubuntu/monitoring-dashboard/Dockerfile
> Remove unsupported JDK versions from Ubuntu dockerfile

- dockerfiles/alpine/micro-integrator/Dockerfile
> Change the Docker base image to Alpine and add OpenJDK11U-jdk_x64_linux_hotspot_2021-05-07-07-34.tar.gz

- CHANGELOG.md
> Update change log for 7.0.x

- CHANGELOG.md
> Update change log for 6.6.x

- CHANGELOG.md
> Update change log for 6.5.x

- CHANGELOG.md
> Update change log for 6.4.x

- CHANGELOG.md
> Update change log for 6.3.x

- CHANGELOG.md
> Update change log for 6.2.x

- CHANGELOG.md
> Update change log for 4.0.1.x

- CHANGELOG.md
> Update change log for 4.0.x

- CHANGELOG.md
- dockerfiles/alpine/analytics-dashboard/Dockerfile
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/monitoring-dashboard/Dockerfile
- dockerfiles/centos/analytics-dashboard/Dockerfile
- dockerfiles/centos/micro-integrator/Dockerfile
- dockerfiles/centos/monitoring-dashboard/Dockerfile
- dockerfiles/ubuntu/analytics-dashboard/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/monitoring-dashboard/Dockerfile
> Update label tag and change log in 7.1.x

- CHANGELOG.md
> Update master change log with v4.0.0.3 

- CHANGELOG.md
- README.md
- dockerfiles/alpine/mi-dashboard/Dockerfile
- dockerfiles/alpine/mi-dashboard/README.md
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/micro-integrator/README.md
- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/alpine/streaming-integrator/README.md
- dockerfiles/centos/mi-dashboard/Dockerfile
- dockerfiles/centos/mi-dashboard/README.md
- dockerfiles/centos/micro-integrator/Dockerfile
- dockerfiles/centos/micro-integrator/README.md
- dockerfiles/centos/streaming-integrator/Dockerfile
- dockerfiles/centos/streaming-integrator/Readme.md
- dockerfiles/ubuntu/mi-dashboard/Dockerfile
- dockerfiles/ubuntu/mi-dashboard/README.md
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/micro-integrator/README.md
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/README.md
> To support MI 4.1.0-beta and SI 4.1.0-beta in Docker images.
> Add support for 4.1.0-beta 

- CHANGELOG.md
- README.md
- dockerfiles/alpine/mi-dashboard/Dockerfile
- dockerfiles/alpine/mi-dashboard/README.md
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/micro-integrator/README.md
- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/alpine/streaming-integrator/README.md
- dockerfiles/centos/mi-dashboard/Dockerfile
- dockerfiles/centos/mi-dashboard/README.md
- dockerfiles/centos/micro-integrator/Dockerfile
- dockerfiles/centos/micro-integrator/README.md
- dockerfiles/centos/streaming-integrator/Dockerfile
- dockerfiles/centos/streaming-integrator/Readme.md
- dockerfiles/ubuntu/mi-dashboard/Dockerfile
- dockerfiles/ubuntu/mi-dashboard/README.md
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/micro-integrator/README.md
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/README.md
> Merge 4.1.x branch to the master in order to prepare for the 4.1.0 release.
> Merge 4.1.x branch to the master 

- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/centos/micro-integrator/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
> Upgrade JDK to 11.0.19+7 and upgrade Ubuntu to 22.04
> [MI][4.1.0] upgrade JDK and Ubuntu

- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/centos/micro-integrator/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
> Upgrade JDK to 11.0.19+7 and upgrade Ubuntu to 22.04
> [MI][4.0.0] upgrade JDK and Ubuntu

- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/centos/micro-integrator/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
> Upgrade JDK to 11.0.20+8
Fixes wso2/micro-integrator/issues/3003
> [MI][4.1.0] Upgrade JDK version

- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/centos/micro-integrator/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
Upgrade alpine image version to 3.18.5 and JDK version to 11.0.21+9
> Update JDK version and alpine image version

- dockerfiles/alpine/micro-integrator/Dockerfile
> To upgrade alpine image version to 3.18.5.
> Upgrade alpine image version

- dockerfiles/ubuntu/micro-integrator/Dockerfile
Update ubuntu dockerfile to get continuous upgrades
> Update ubuntu dockerfile to get continuous upgrades

- dockerfiles/alpine/streaming-integrator/Dockerfile
This PR upgrades the alpine version to 3.19.0 of SI image.
Related issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/5226
> [4.2.x] Upgrade alpine version to 3.19.0

- CHANGELOG.md
- dockerfiles/alpine/mi-dashboard/Dockerfile
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/centos/mi-dashboard/Dockerfile
- dockerfiles/centos/micro-integrator/Dockerfile
- dockerfiles/centos/streaming-integrator/Dockerfile
- dockerfiles/ubuntu/mi-dashboard/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
> Updates ubuntu and centOS dockerfiles of MI dashboard and SI to get continuous upgrades.
> [4.2.x] Update dockerfiles to get continuous upgrades (Dashboard & SI)

- dockerfiles/centos/mi-dashboard/Dockerfile
- dockerfiles/centos/micro-integrator/Dockerfile
- dockerfiles/centos/streaming-integrator/Dockerfile
- dockerfiles/ubuntu/mi-dashboard/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
> This PR updates the ubuntu and centOS dockerfiles to get continuous upgrades.
> Update dockerfiles to get continuous upgrades 

- CHANGELOG.md
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/centos/micro-integrator/Dockerfile
- dockerfiles/centos/streaming-integrator/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
> This PR updates the ubuntu dockerfiles to get continuous upgrades.
ports https://github.com/wso2/docker-ei/pull/337
> [7.0.x] Update ubuntu docker files to get continuous upgrades

- CHANGELOG.md
- dockerfiles/alpine/analytics-dashboard/Dockerfile
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/monitoring-dashboard/Dockerfile
- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/centos/analytics-dashboard/Dockerfile
- dockerfiles/centos/micro-integrator/Dockerfile
- dockerfiles/centos/monitoring-dashboard/Dockerfile
- dockerfiles/centos/streaming-integrator/Dockerfile
- dockerfiles/ubuntu/analytics-dashboard/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/monitoring-dashboard/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
> This PR updates the ubuntu dockerfiles to get continuous upgrades.
ports https://github.com/wso2/docker-ei/pull/337
> [7.1.x] Update ubuntu dockerfiles to get continuous upgrades

- dockerfiles/alpine/analytics/dashboard/Dockerfile
- dockerfiles/alpine/analytics/worker/Dockerfile
- dockerfiles/alpine/broker/Dockerfile
- dockerfiles/alpine/business-process/Dockerfile
- dockerfiles/alpine/integrator/Dockerfile
- dockerfiles/centos/analytics/dashboard/Dockerfile
- dockerfiles/centos/analytics/worker/Dockerfile
- dockerfiles/centos/broker/Dockerfile
- dockerfiles/centos/business-process/Dockerfile
- dockerfiles/centos/integrator/Dockerfile
- dockerfiles/ubuntu/analytics/dashboard/Dockerfile
- dockerfiles/ubuntu/analytics/worker/Dockerfile
- dockerfiles/ubuntu/broker/Dockerfile
- dockerfiles/ubuntu/business-process/Dockerfile
- dockerfiles/ubuntu/integrator/Dockerfile
> Remove MySQL JDBC connector from docker images.
Related issue: https://github.com/wso2-enterprise/wso2-mi-internal/issues/528
> Remove MySQL JDBC connector from docker images

- dockerfiles/alpine/analytics/dashboard/Dockerfile
- dockerfiles/alpine/analytics/worker/Dockerfile
- dockerfiles/alpine/broker/Dockerfile
- dockerfiles/alpine/business-process/Dockerfile
- dockerfiles/alpine/integrator/Dockerfile
- dockerfiles/centos/analytics/dashboard/Dockerfile
- dockerfiles/centos/analytics/worker/Dockerfile
- dockerfiles/centos/broker/Dockerfile
- dockerfiles/centos/business-process/Dockerfile
- dockerfiles/centos/integrator/Dockerfile
- dockerfiles/ubuntu/analytics/dashboard/Dockerfile
- dockerfiles/ubuntu/analytics/worker/Dockerfile
- dockerfiles/ubuntu/broker/Dockerfile
- dockerfiles/ubuntu/business-process/Dockerfile
- dockerfiles/ubuntu/integrator/Dockerfile
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
$subject
> Upgrade kubernetes membership schema jar and update release tag versions

- dockerfiles/rocky/mi-dashboard/Dockerfile
- dockerfiles/rocky/mi-dashboard/README.md
- dockerfiles/rocky/mi-dashboard/docker-entrypoint.sh
- dockerfiles/rocky/micro-integrator/Dockerfile
- dockerfiles/rocky/micro-integrator/README.md
- dockerfiles/rocky/micro-integrator/docker-entrypoint.sh
> Add RockyLinux image for MI 4.2.0
> Add RockyLinux image for MI 4.2.0

- CHANGELOG.md
- dockerfiles/alpine/mi-dashboard/Dockerfile
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/centos/mi-dashboard/Dockerfile
- dockerfiles/centos/micro-integrator/Dockerfile
- dockerfiles/centos/streaming-integrator/Dockerfile
- dockerfiles/ubuntu/mi-dashboard/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
> Increment release tag

- dockerfiles/rocky/mi-dashboard/Dockerfile
Add Rocky Linux to MI-Dashboard 4.2.0
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc …
> Add Rocky Linux to MI-Dashboard 4.2.0

- dockerfiles/alpine/mi-dashboard/Dockerfile
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/rocky/mi-dashboard/Dockerfile
- dockerfiles/rocky/micro-integrator/Dockerfile
- dockerfiles/ubuntu/mi-dashboard/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
> Change rocky version to LTS (8.10)
> Change rocky version to LTS (8.10)

- dockerfiles/alpine/mi-dashboard/Dockerfile
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/rocky/mi-dashboard/Dockerfile
- dockerfiles/rocky/micro-integrator/Dockerfile
- dockerfiles/ubuntu/mi-dashboard/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
Fix rockyLinux repository
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter …
> Fix rockyLinux repository

- dockerfiles/alpine/mi-dashboard/Dockerfile
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/rocky/mi-dashboard/Dockerfile
- dockerfiles/rocky/mi-dashboard/README.md
- dockerfiles/rocky/mi-dashboard/docker-entrypoint.sh
- dockerfiles/rocky/micro-integrator/Dockerfile
- dockerfiles/rocky/micro-integrator/README.md
- dockerfiles/rocky/micro-integrator/docker-entrypoint.sh
- dockerfiles/rocky/streaming-integrator/Dockerfile
- dockerfiles/rocky/streaming-integrator/Readme.md
- dockerfiles/rocky/streaming-integrator/docker-entrypoint.sh
- dockerfiles/ubuntu/mi-dashboard/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
> Add RockyLinux to MI 4.1.0

- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/rocky/micro-integrator/Dockerfile
- dockerfiles/rocky/micro-integrator/README.md
- dockerfiles/rocky/micro-integrator/docker-entrypoint.sh
- dockerfiles/rocky/streaming-integrator/Dockerfile
- dockerfiles/rocky/streaming-integrator/Readme.md
- dockerfiles/rocky/streaming-integrator/docker-entrypoint.sh
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
Add RockyLinux for MI 1.0.0
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter …
> Add RockyLinux for MI 1.0.0

- dockerfiles/alpine/analytics-dashboard/Dockerfile
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/monitoring-dashboard/Dockerfile
- dockerfiles/rocky/analytics-dashboard/Dockerfile
- dockerfiles/rocky/analytics-dashboard/README.md
- dockerfiles/rocky/analytics-dashboard/docker-entrypoint.sh
- dockerfiles/rocky/micro-integrator/Dockerfile
- dockerfiles/rocky/micro-integrator/README.md
- dockerfiles/rocky/micro-integrator/docker-entrypoint.sh
- dockerfiles/rocky/monitoring-dashboard/Dockerfile
- dockerfiles/rocky/monitoring-dashboard/README.md
- dockerfiles/rocky/monitoring-dashboard/docker-entrypoint.sh
- dockerfiles/rocky/streaming-integrator/Dockerfile
- dockerfiles/rocky/streaming-integrator/Readme.md
- dockerfiles/rocky/streaming-integrator/docker-entrypoint.sh
- dockerfiles/ubuntu/analytics-dashboard/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/monitoring-dashboard/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
> Add RockyLinux to MI 1.2.0

- dockerfiles/alpine/mi-dashboard/Dockerfile
- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/rocky/mi-dashboard/Dockerfile
- dockerfiles/rocky/mi-dashboard/README.md
- dockerfiles/rocky/mi-dashboard/docker-entrypoint.sh
- dockerfiles/rocky/micro-integrator/Dockerfile
- dockerfiles/rocky/micro-integrator/README.md
- dockerfiles/rocky/micro-integrator/docker-entrypoint.sh
- dockerfiles/rocky/streaming-integrator/Dockerfile
- dockerfiles/rocky/streaming-integrator/Readme.md
- dockerfiles/rocky/streaming-integrator/docker-entrypoint.sh
- dockerfiles/ubuntu/mi-dashboard/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
> Add RockyLinux images for MI 4.0.0
> Add RockyLinux images for MI 4.0.0

- dockerfiles/rocky/mi-dashboard/Dockerfile
- dockerfiles/rocky/mi-dashboard/README.md
- dockerfiles/rocky/mi-dashboard/docker-entrypoint.sh
- dockerfiles/ubuntu/mi-dashboard/Dockerfile
> Add RockyLinux for MI-Dashboard 4.0.1
> Add RockyLinux for MI-Dashboard 4.0.1

- dockerfiles/alpine/analytics/dashboard/Dockerfile
- dockerfiles/alpine/analytics/worker/Dockerfile
- dockerfiles/alpine/broker/Dockerfile
- dockerfiles/alpine/business-process/Dockerfile
- dockerfiles/alpine/integrator/Dockerfile
- dockerfiles/rocky/analytics/dashboard/Dockerfile
- dockerfiles/rocky/analytics/dashboard/README.md
- dockerfiles/rocky/analytics/dashboard/docker-entrypoint.sh
- dockerfiles/rocky/analytics/worker/Dockerfile
- dockerfiles/rocky/analytics/worker/README.md
- dockerfiles/rocky/analytics/worker/docker-entrypoint.sh
- dockerfiles/rocky/broker/Dockerfile
- dockerfiles/rocky/broker/README.md
- dockerfiles/rocky/broker/docker-entrypoint.sh
- dockerfiles/rocky/business-process/Dockerfile
- dockerfiles/rocky/business-process/README.md
- dockerfiles/rocky/business-process/docker-entrypoint.sh
- dockerfiles/rocky/integrator/Dockerfile
- dockerfiles/rocky/integrator/README.md
- dockerfiles/rocky/integrator/docker-entrypoint.sh
- dockerfiles/ubuntu/analytics/dashboard/Dockerfile
- dockerfiles/ubuntu/business-process/Dockerfile
- dockerfiles/ubuntu/integrator/Dockerfile
> Add RockyLinux for EI 6.6.0

- dockerfiles/alpine/micro-integrator/Dockerfile
> To obtain latest OS updates in docker build time.
> Keep base image upto date.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have provided …
> Add instructions to get latest OS updates in docker build

- dockerfiles/alpine/mi-dashboard/Dockerfile
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/rocky/mi-dashboard/Dockerfile
- dockerfiles/rocky/micro-integrator/Dockerfile
- dockerfiles/rocky/streaming-integrator/Dockerfile
- dockerfiles/ubuntu/mi-dashboard/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
> Update ubuntu docker images to get continuous upgrades

- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/centos/micro-integrator/Dockerfile
- dockerfiles/rocky/micro-integrator/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
> [MI-1.2.0] Update alpine docker images to get continuous upgrades

- dockerfiles/alpine/mi-dashboard/Dockerfile
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/rocky/mi-dashboard/Dockerfile
- dockerfiles/rocky/micro-integrator/Dockerfile
- dockerfiles/ubuntu/mi-dashboard/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- Updates JDK version to v11.0.25
- Updates alpine version to v3.18.9
> Update JDK version of the MI dashboard images

- dockerfiles/alpine/analytics/dashboard/Dockerfile
- dockerfiles/alpine/analytics/worker/Dockerfile
- dockerfiles/alpine/broker/Dockerfile
- dockerfiles/alpine/business-process/Dockerfile
- dockerfiles/alpine/integrator/Dockerfile
- dockerfiles/rocky/analytics/dashboard/Dockerfile
- dockerfiles/rocky/analytics/worker/Dockerfile
- dockerfiles/rocky/broker/Dockerfile
- dockerfiles/rocky/business-process/Dockerfile
- dockerfiles/rocky/integrator/Dockerfile
- dockerfiles/ubuntu/analytics/dashboard/Dockerfile
- dockerfiles/ubuntu/analytics/worker/Dockerfile
- dockerfiles/ubuntu/broker/Dockerfile
- dockerfiles/ubuntu/business-process/Dockerfile
- dockerfiles/ubuntu/integrator/Dockerfile
> [EI-6.6.0] Update Ubuntu docker images to get continuous updates

- dockerfiles/alpine/mi-dashboard/Dockerfile
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/centos/mi-dashboard/Dockerfile
- dockerfiles/centos/micro-integrator/Dockerfile
- dockerfiles/centos/streaming-integrator/Dockerfile
- dockerfiles/ubuntu/mi-dashboard/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
$subject. This supports the MI project deploying in Choreo as a BYOC workflow.
Related issue: https://github.com/wso2-enterprise/integration-product-management/issues/180
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
> Change the userID to between 10000 and 20000

- CHANGELOG.md
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/micro-integrator/README.md
- dockerfiles/rocky/micro-integrator/Dockerfile
- dockerfiles/rocky/micro-integrator/README.md
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/micro-integrator/README.md
> $subject
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
> Update MI version to 4.4.0 and bump OS and JDK versions

- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/rocky/micro-integrator/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
> $Subject
Fixes: #370
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
> Fix issues encountered when running helm charts

- dockerfiles/alpine/mi-dashboard/Dockerfile
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/rocky/mi-dashboard/Dockerfile
- dockerfiles/rocky/micro-integrator/Dockerfile
- dockerfiles/ubuntu/mi-dashboard/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
> Upgrade ubuntu version to next LTS 24.04
> Upgrade ubuntu version to next LTS

- dockerfiles/alpine/mi-dashboard/Dockerfile
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/streaming-integrator/Dockerfile
- dockerfiles/rocky/mi-dashboard/Dockerfile
- dockerfiles/rocky/micro-integrator/Dockerfile
- dockerfiles/ubuntu/mi-dashboard/Dockerfile
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/streaming-integrator/Dockerfile
> Allow continuous updating packages in WSO2 MI 4.2.0 Alpine Docker Image

- CHANGELOG.md
- dockerfiles/alpine/micro-integrator/Dockerfile
- dockerfiles/alpine/micro-integrator/README.md
- dockerfiles/rocky/micro-integrator/Dockerfile
- dockerfiles/rocky/micro-integrator/README.md
- dockerfiles/ubuntu/micro-integrator/Dockerfile
- dockerfiles/ubuntu/micro-integrator/README.md
> Prepare for release 4.5.0
