dockerfile/Dockerfile, dockerfile/common/wso2base/Dockerfile, dockerfile/common/wso2base/build.sh
This PR fixes the `wso2/wso2base` image name to suit the changes done in [1]. Resolves #10 
Please refer [1].
Please refer [1].
Please refer [1].
Please refer [1].
N/A
N/A
N/A
N/A
N/A
N/A
N/A
[1]
N/A
Ubuntu 16.04.3 LTS
Docker version: 17.05.0-ce Built: Thu May  4 22:10:54 2017
N/A
[1] - https://github.com/wso2/docker-common/pull/17
=> Fix base image name to ubuntu-16.04 based one

dockerfiles/README.md
In " Running docker images specific to each profile" -> For analytics, the parameter that passes changed to wso2ei-analytics:6.1.1
=> wso2ei-analytics:6.1.1 changed in running docker images

docker-compose/integrator-broker-bps-analytics/README.md, docker-compose/integrator-broker-bps-analytics/analytics/conf/user-mgt.xml, docker-compose/integrator-broker-bps-analytics/broker/conf/broker.xml, docker-compose/integrator-broker-bps-analytics/broker/conf/user-mgt.xml, docker-compose/integrator-broker-bps-analytics/business-process/conf/carbon.xml, docker-compose/integrator-broker-bps-analytics/business-process/conf/user-mgt.xml, docker-compose/integrator-broker-bps-analytics/docker-compose.yml, docker-compose/integrator-broker-bps-analytics/integrator/conf/axis2/axis2.xml, docker-compose/integrator-broker-bps-analytics/integrator/conf/carbon.xml, docker-compose/integrator-broker-bps-analytics/integrator/conf/user-mgt.xml, docker-compose/integrator-broker-bps-analytics/integrator/repository/deployment/server/eventpublishers/MessageFlowConfigurationPublisher.xml, docker-compose/integrator-broker-bps-analytics/integrator/repository/deployment/server/eventpublishers/MessageFlowStatisticsPublisher.xml
> Migrate WSO2 Enterprise Integrator For Integration, Broker and Business Process (BPS) use-cases with Analytics deployment to WSO2 EI version 6.2.0. This closes https://github.com/wso2/docker-ei/issues/46.
> Migrate Docker Compose resources from WSO2 Enterprise Integrator version 6.1.1 to version 6.2.0.
=> Migrate WSO2 Enterprise Integrator For Integration, Broker and Business Process (BPS) use-cases with Analytics deployment to WSO2 EI version 6.2.0

dockerfiles/base/Dockerfile, dockerfiles/integrator/init.sh
> In this PR, Kubernetes membership scheme JAR file is prepackaged in the Docker image. Further, artifacts to be shared during clustering have been moved to a temporary location prior to packaging. This closes https://github.com/wso2/docker-ei/issues/58 and closes https://github.com/wso2/docker-ei/issues/59.
> Prepare the Docker image for Integrator profile for clustering
=> Prepare the Docker image for Integrator profile for clustering

dockerfiles/base/Dockerfile
> Install Netcat tool required for container health checks. This closes https://github.com/wso2/docker-ei/issues/62.
> Install Netcat tool required for container health checks.
=> Install Netcat tool required for container health checks

dockerfiles/README.md, dockerfiles/base/Dockerfile, dockerfiles/business-process/Dockerfile, dockerfiles/business-process/init.sh, dockerfiles/integrator/Dockerfile, dockerfiles/integrator/init.sh
> Prepare business process server profile Docker image for artifact sharing during clustering. This closes https://github.com/wso2/docker-ei/issues/65.
> Prepare business process server profile Docker image for artifact sharing during clustering.
> When clustering the Integrator profile using container cluster management platforms, it was decided to prepackage the artifacts to be shared in a temporary location. This set of artifacts in turn would be copied to the shared volume mount (at the original location), during the deployment. The same approach has been used for business process product profile as well.
=> Prepare business process server profile Docker image for artifact sharing

dockerfiles/analytics/Dockerfile, dockerfiles/analytics/init.sh, dockerfiles/base/Dockerfile, dockerfiles/broker/init.sh, dockerfiles/business-process/init.sh, dockerfiles/integrator/Dockerfile, dockerfiles/integrator/init.sh
> Prepare WSO2 Enterprise Integrator version 6.3.x Docker resources for clustering in Kubernetes platform. This fixes https://github.com/wso2/docker-ei/issues/73.
> Prepare WSO2 Enterprise Integrator version 6.3.x Docker resources for clustering in Kubernetes platform.
=> Prepare WSO2 Enterprise Integrator version 6.3.x Docker resources for clustering in Kubernetes platform

docker-compose/integrator-analytics/docker-compose.yml, docker-compose/integrator-bps-analytics/docker-compose.yml, docker-compose/integrator-broker-analytics/docker-compose.yml, docker-compose/integrator-broker-bps-analytics/docker-compose.yml, dockerfiles/analytics/init.sh, dockerfiles/broker/init.sh, dockerfiles/business-process/init.sh, dockerfiles/integrator/init.sh, dockerfiles/msf4j/init.sh
> Rename configuration mount folder in product containers from `volumes` to `wso2-server-volume`.
> Rename configuration mount folder in product containers with a meaningful name.
=> Rename configuration mount folder in product containers

.gitignore, dockerfiles/README.md, dockerfiles/micro-integrator/Dockerfile, dockerfiles/micro-integrator/init.sh
> WSO2 Enterprise Integrator version 6.3.x introduces a new Micro-Integrator profile. Docker resources associated with this profile need to be created. This fixes https://github.com/wso2/docker-ei/issues/81.
> Docker resources for WSO2 Enterprise Integrator version 6.3.x Micro-Integrator profile.
=> Introduce Docker resources for Micro-Integrator profile of WSO2 Enterprise Integrator

docker-compose/integrator-broker-analytics/integrator/conf/axis2/axis2.xml, docker-compose/integrator-broker-bps-analytics/integrator/conf/axis2/axis2.xml
> Add missing configuration of allowing JMS transport of Integrator profile to communicate with the Broker profile.
> Allow JMS transport of Integrator profile to communicate with the Broker profile
=> Allow JMS transport of Integrator profile to communicate with the Broker profile

dockerfiles/alpine/analytics/base/Dockerfile, dockerfiles/alpine/broker/Dockerfile, dockerfiles/alpine/business-process/Dockerfile, dockerfiles/alpine/integrator/Dockerfile, dockerfiles/alpine/msf4j/Dockerfile, dockerfiles/ubuntu/analytics/base/Dockerfile, dockerfiles/ubuntu/broker/Dockerfile, dockerfiles/ubuntu/business-process/Dockerfile, dockerfiles/ubuntu/integrator/Dockerfile, dockerfiles/ubuntu/msf4j/Dockerfile
> Upgrade AdoptOpenJDK version of Alpine and Ubuntu based Docker resources to the latest version - jdk8u212-b03. CentOS based Docker resources have already been tested with the defined version. This fixes https://github.com/wso2/docker-ei/issues/121.
> Upgrade AdoptOpenJDK version to the latest version - jdk8u212-b03
=> Upgrade AdoptOpenJDK version to the latest version - jdk8u212-b03

docker-compose/integrator-analytics/README.md, docker-compose/integrator-analytics/docker-compose.yml, docker-compose/integrator-analytics/scripts/README.md, docker-compose/integrator-analytics/scripts/deploy.sh, docker-compose/integrator-bps-analytics/README.md, docker-compose/integrator-bps-analytics/docker-compose.yml, docker-compose/integrator-bps-analytics/scripts/README.md, docker-compose/integrator-bps-analytics/scripts/deploy.sh, docker-compose/integrator-broker-analytics/docker-compose.yml, docker-compose/integrator-broker-analytics/scripts/README.md, docker-compose/integrator-broker-analytics/scripts/deploy.sh, docker-compose/integrator-broker-bps-analytics/README.md, docker-compose/integrator-broker-bps-analytics/docker-compose.yml, docker-compose/integrator-broker-bps-analytics/scripts/README.md, docker-compose/integrator-broker-bps-analytics/scripts/deploy.sh
> Integrate support in Docker Compose resources for usage of both types of users: users with and without WSO2 subscriptions. Currently, only users with WSO2 subscriptions can utilize Docker Compose resources. This fixes https://github.com/wso2/docker-ei/issues/125.
> Integrate support in Docker Compose resources for users with and without WSO2 subscriptions
=> Integrate support in Docker Compose resources for users with and without WSO2 subscriptions

dockerfiles/alpine/broker/Dockerfile, dockerfiles/alpine/integrator/Dockerfile, dockerfiles/centos/broker/Dockerfile, dockerfiles/centos/integrator/Dockerfile, dockerfiles/ubuntu/broker/Dockerfile, dockerfiles/ubuntu/integrator/Dockerfile
> Add artifacts required for WSO2 Kubernetes membership scheme to Broker and Integrator profile Docker resources. This fixes https://github.com/wso2/docker-ei/issues/142.
> Package the Kubernetes Membership Scheme in Broker and Integrator profile Docker images
=> Add artifacts required for WSO2 Kubernetes membership scheme to Broker and Integrator profile Docker resources

dockerfiles/alpine/micro-integrator/docker-entrypoint.sh
> The proper way to allow commands to be executed in a container is to add `exec "$@"` at the end of its `entrypoint.sh`. Without it, there is no real flexible use of this image
> make things clean
> Apply syntax properly [references](https://wiki.bash-hackers.org/commands/builtin/exec)
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the …
=> Make command input possible

dockerfiles/ubuntu/integrator/Dockerfile
http://central.maven.org/ does not exist anymore - changed to https://repo1.maven.org/
central.maven.org is not available anymore
to make docker build work
=> Changed central.maven.org to repo1.maven.org

dockerfiles/alpine/analytics-dashboard/Dockerfile, dockerfiles/alpine/micro-integrator/Dockerfile, dockerfiles/alpine/monitoring-dashboard/Dockerfile, dockerfiles/alpine/streaming-integrator/Dockerfile, dockerfiles/centos/analytics-dashboard/Dockerfile, dockerfiles/centos/micro-integrator/Dockerfile, dockerfiles/centos/monitoring-dashboard/Dockerfile, dockerfiles/centos/streaming-integrator/Dockerfile, dockerfiles/ubuntu/analytics-dashboard/Dockerfile, dockerfiles/ubuntu/micro-integrator/Dockerfile, dockerfiles/ubuntu/monitoring-dashboard/Dockerfile, dockerfiles/ubuntu/streaming-integrator/Dockerfile
> This PR introduces the Docker source Git release tag as a label. This fixes #207  
> Introduce the Docker source Git release tag as a label. 
> Use the dockerfile instruction `LABEL` to add the Git release tag as a label.
Server: Docker Engine - Community
Engine:
Built:            Mon Jun 22 15:44:07 2020
OS/Arch:          linux/amd64
Experimental:     false
containerd:
Version:          1.2.13
GitCommit: …
=> [7.1.0] Add Git release tag as a label

dockerfiles/alpine/analytics-dashboard/Dockerfile, dockerfiles/alpine/micro-integrator/Dockerfile, dockerfiles/alpine/monitoring-dashboard/Dockerfile, dockerfiles/alpine/streaming-integrator/Dockerfile, dockerfiles/centos/analytics-dashboard/Dockerfile, dockerfiles/centos/micro-integrator/Dockerfile, dockerfiles/centos/monitoring-dashboard/Dockerfile, dockerfiles/centos/streaming-integrator/Dockerfile, dockerfiles/ubuntu/analytics-dashboard/Dockerfile, dockerfiles/ubuntu/micro-integrator/Dockerfile, dockerfiles/ubuntu/monitoring-dashboard/Dockerfile, dockerfiles/ubuntu/streaming-integrator/Dockerfile
> This PR enables SSL verification for `wget`. This fixes #206 
> Enable SSL verification for `wget`.
> Removes existing option `--no-check-certificate` for `wget`. 
Server: Docker Engine - Community
Engine:
Built:            Mon Jun 22 15:44:07 2020
OS/Arch:          linux/amd64
Experimental:     false
containerd:
Version:          1.2.13
GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
runc:
Version: …
=> [7.1.0] Enable for SSL verification for wget

dockerfiles/alpine/analytics-dashboard/Dockerfile, dockerfiles/alpine/micro-integrator/Dockerfile, dockerfiles/alpine/monitoring-dashboard/Dockerfile, dockerfiles/alpine/streaming-integrator/Dockerfile, dockerfiles/centos/analytics-dashboard/Dockerfile, dockerfiles/centos/micro-integrator/Dockerfile, dockerfiles/centos/monitoring-dashboard/Dockerfile, dockerfiles/centos/streaming-integrator/Dockerfile, dockerfiles/ubuntu/analytics-dashboard/Dockerfile, dockerfiles/ubuntu/micro-integrator/Dockerfile, dockerfiles/ubuntu/monitoring-dashboard/Dockerfile, dockerfiles/ubuntu/streaming-integrator/Dockerfile
> This PR introduces Github as the source for GA products pack downloads. This fixes #208 
> Download the GA products pack from Github.
Server: Docker Engine - Community
Engine:
Built:            Mon Jun 22 15:44:07 2020
OS/Arch:          linux/amd64
Experimental:     false
containerd:
Version:          1.2.13
GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
runc:
Version:          1.0.0-rc10
GitCommit: …
=> [7.1.0] Download product pack from Github

dockerfiles/alpine/analytics/dashboard/Dockerfile, dockerfiles/alpine/analytics/worker/Dockerfile, dockerfiles/alpine/broker/Dockerfile, dockerfiles/alpine/business-process/Dockerfile, dockerfiles/alpine/integrator/Dockerfile, dockerfiles/centos/analytics/dashboard/Dockerfile, dockerfiles/centos/analytics/worker/Dockerfile, dockerfiles/centos/broker/Dockerfile, dockerfiles/centos/business-process/Dockerfile, dockerfiles/centos/integrator/Dockerfile, dockerfiles/ubuntu/analytics/dashboard/Dockerfile, dockerfiles/ubuntu/analytics/worker/Dockerfile, dockerfiles/ubuntu/broker/Dockerfile, dockerfiles/ubuntu/business-process/Dockerfile, dockerfiles/ubuntu/integrator/Dockerfile
> This PR introduces the Docker source Git release tag as a label and enable SSL verification for wget. 
> This fixes #215, #219 
> Introduce the Docker source Git release tag as a label.
> Enable SSL verification for wget.
> Use the dockerfile instruction LABEL to add Git release tag as a label.
> Removes existing option --no-check-certificate for wget.
> Server: Docker Engine - Community
Engine:
Built:            Mon …
=> [6.6.0] Add Git release tag as a label and enable SSL verification for wget

dockerfiles/alpine/analytics/dashboard/Dockerfile, dockerfiles/alpine/analytics/worker/Dockerfile, dockerfiles/alpine/broker/Dockerfile, dockerfiles/alpine/business-process/Dockerfile, dockerfiles/alpine/integrator/Dockerfile, dockerfiles/alpine/msf4j/Dockerfile, dockerfiles/centos/analytics/dashboard/Dockerfile, dockerfiles/centos/analytics/worker/Dockerfile, dockerfiles/centos/broker/Dockerfile, dockerfiles/centos/business-process/Dockerfile, dockerfiles/centos/integrator/Dockerfile, dockerfiles/centos/msf4j/Dockerfile, dockerfiles/ubuntu/analytics/dashboard/Dockerfile, dockerfiles/ubuntu/analytics/worker/Dockerfile, dockerfiles/ubuntu/broker/Dockerfile, dockerfiles/ubuntu/business-process/Dockerfile, dockerfiles/ubuntu/integrator/Dockerfile, dockerfiles/ubuntu/msf4j/Dockerfile
> This PR introduces the Docker source Git release tag as a label and enable SSL verification for wget. 
> This fixes #216, #220 
> Introduce the Docker source Git release tag as a label.
> Enable SSL verification for wget.
> Use the dockerfile instruction LABEL to add Git release tag as a label.
> Removes existing option --no-check-certificate for wget.
> Server: Docker Engine - Community
Engine:
Built:            Mon …
=> [6.5.0] Add Git release tag as a label and enable SSL verification for wget

dockerfiles/alpine/micro-integrator/Dockerfile, dockerfiles/alpine/streaming-integrator/Dockerfile, dockerfiles/centos/micro-integrator/Dockerfile, dockerfiles/centos/streaming-integrator/Dockerfile, dockerfiles/ubuntu/micro-integrator/Dockerfile, dockerfiles/ubuntu/streaming-integrator/Dockerfile
> This PR introduces the Docker source Git release tag as a label and enable SSL verification for wget. 
> This fixes #212 , #213 
> Introduce the Docker source Git release tag as a label.
> Enable SSL verification for wget.
> Use the dockerfile instruction LABEL to add Git release tag as a label.
> Removes existing option --no-check-certificate for wget.
> add CA-certificates to alpine base image
> Server: Docker Engine - Community
Engine:
Git …
=> [7.0.0] Add Git release tag as a label and enable SSL verification for wget

dockerfiles/alpine/analytics-dashboard/docker-entrypoint.sh, dockerfiles/alpine/micro-integrator/docker-entrypoint.sh, dockerfiles/alpine/monitoring-dashboard/docker-entrypoint.sh
> This PR fixes #229 
> Pass CMD args to the server startup script for Alpine based images.
> Start server startup script as `sh ${WSO2_SERVER_STRATUP_SCRIPT} "$@"`
Version:           18.09.2
API version:       1.39
Go version:        go1.10.8
Git commit:        6247962
Built:             Sun Feb 10 04:12:39 2019
OS/Arch:           darwin/amd64
Experimental:      true
> Server: Docker Engine - Community
Engine:
Version:          18.09.2
API version:      1.39 (minimum version 1.12)
Go version:       go1.10.6
Git commit:       6247962
Built:            Sun Feb 10 04:13:06 2019
OS/Arch:          linux/amd64
Experimental:     false
=> [7.1.0] Fix server starting command

CHANGELOG.md
> Update CHANGELOG for the latest release
> Create release for docker-ei 6.6.0.4
=> [6.6.0] Update CHANGELOG for the latest release(6.6.0.4)

CHANGELOG.md, README.md, dockerfiles/alpine/micro-integrator/Dockerfile, dockerfiles/alpine/streaming-integrator/Dockerfile, dockerfiles/centos/micro-integrator/Dockerfile, dockerfiles/centos/streaming-integrator/Dockerfile, dockerfiles/ubuntu/micro-integrator/Dockerfile, dockerfiles/ubuntu/streaming-integrator/Dockerfile
- Upgrade base OS images to jdk-11.0.9_11 in MI and SI
- Prepare for the 7.0.0.4 release.
Resolves https://github.com/wso2/docker-ei/issues/257
=> Upgrade base OS images & prepare for the 7.0.0.4 release

CHANGELOG.md, dockerfiles/alpine/analytics-dashboard/Dockerfile, dockerfiles/alpine/micro-integrator/Dockerfile, dockerfiles/alpine/monitoring-dashboard/Dockerfile, dockerfiles/alpine/streaming-integrator/Dockerfile, dockerfiles/centos/analytics-dashboard/Dockerfile, dockerfiles/centos/micro-integrator/Dockerfile, dockerfiles/centos/monitoring-dashboard/Dockerfile, dockerfiles/centos/streaming-integrator/Dockerfile, dockerfiles/ubuntu/analytics-dashboard/Dockerfile, dockerfiles/ubuntu/micro-integrator/Dockerfile, dockerfiles/ubuntu/monitoring-dashboard/Dockerfile, dockerfiles/ubuntu/streaming-integrator/Dockerfile
This PR updates the base version of MI-1.2.0 docker images as below,
Ubuntu: adoptopenjdk:11.0.10_9-jdk-hotspot-focal
Alpine: adoptopenjdk/openjdk11:jdk-11.0.10_9-alpine
Centos: adoptopenjdk/openjdk11:x86_64-centos-jdk-11.0.10_9
=> Update base image version for MI-1.2.0

dockerfiles/alpine/analytics-dashboard/Dockerfile, dockerfiles/alpine/micro-integrator/Dockerfile, dockerfiles/alpine/monitoring-dashboard/Dockerfile, dockerfiles/alpine/streaming-integrator/Dockerfile, dockerfiles/centos/analytics-dashboard/Dockerfile, dockerfiles/centos/micro-integrator/Dockerfile, dockerfiles/centos/monitoring-dashboard/Dockerfile, dockerfiles/centos/streaming-integrator/Dockerfile, dockerfiles/ubuntu/analytics-dashboard/Dockerfile, dockerfiles/ubuntu/micro-integrator/Dockerfile, dockerfiles/ubuntu/monitoring-dashboard/Dockerfile, dockerfiles/ubuntu/streaming-integrator/Dockerfile
=> [7.1.x] Modify Dockerfiles to use base OS image and build Temurin OpenJDK 11

dockerfiles/alpine/micro-integrator/Dockerfile, dockerfiles/alpine/streaming-integrator/Dockerfile, dockerfiles/centos/micro-integrator/Dockerfile, dockerfiles/centos/streaming-integrator/Dockerfile, dockerfiles/ubuntu/micro-integrator/Dockerfile, dockerfiles/ubuntu/streaming-integrator/Dockerfile
=> [7.0.x] Modify Dockerfiles to use base OS image and build Temurin OpenJDK 11 

dockerfiles/alpine/mi-dashboard/Dockerfile, dockerfiles/alpine/micro-integrator/Dockerfile, dockerfiles/alpine/streaming-integrator/Dockerfile, dockerfiles/centos/mi-dashboard/Dockerfile, dockerfiles/centos/micro-integrator/Dockerfile, dockerfiles/centos/streaming-integrator/Dockerfile, dockerfiles/ubuntu/mi-dashboard/Dockerfile, dockerfiles/ubuntu/micro-integrator/Dockerfile, dockerfiles/ubuntu/streaming-integrator/Dockerfile
=> [4.0.x] Modify Dockerfiles to use base OS image and build Temurin OpenJDK 11 

dockerfiles/alpine/mi-dashboard/Dockerfile, dockerfiles/centos/mi-dashboard/Dockerfile, dockerfiles/ubuntu/mi-dashboard/Dockerfile
=> [4.0.1.x] Modify Dockerfiles to use base OS image and build Temurin OpenJDK 11 

dockerfiles/alpine/analytics/Dockerfile, dockerfiles/alpine/integrator/Dockerfile, dockerfiles/centos/analytics/Dockerfile, dockerfiles/centos/integrator/Dockerfile, dockerfiles/ubuntu/analytics/Dockerfile, dockerfiles/ubuntu/integrator/Dockerfile
=> [6.2.x] Modify Dockerfiles to use base OS image and build Temurin OpenJDK 8

dockerfiles/analytics/Dockerfile, dockerfiles/integrator/Dockerfile, dockerfiles/micro-integrator/Dockerfile
=> [6.3.x] Modify Dockerfiles to use base OS image and build Temurin OpenJDK 8

dockerfiles/alpine/analytics/dashboard/Dockerfile, dockerfiles/alpine/analytics/worker/Dockerfile, dockerfiles/alpine/integrator/Dockerfile, dockerfiles/alpine/micro-integrator/Dockerfile, dockerfiles/centos/analytics/dashboard/Dockerfile, dockerfiles/centos/analytics/worker/Dockerfile, dockerfiles/centos/integrator/Dockerfile, dockerfiles/centos/micro-integrator/Dockerfile, dockerfiles/ubuntu/analytics/dashboard/Dockerfile, dockerfiles/ubuntu/analytics/worker/Dockerfile, dockerfiles/ubuntu/integrator/Dockerfile, dockerfiles/ubuntu/micro-integrator/Dockerfile
=> [6.4.x] Modify Dockerfiles to use base OS image and build Temurin OpenJDK 8 

dockerfiles/alpine/analytics/dashboard/Dockerfile, dockerfiles/alpine/analytics/worker/Dockerfile, dockerfiles/alpine/integrator/Dockerfile, dockerfiles/centos/analytics/dashboard/Dockerfile, dockerfiles/centos/analytics/worker/Dockerfile, dockerfiles/centos/integrator/Dockerfile, dockerfiles/ubuntu/analytics/dashboard/Dockerfile, dockerfiles/ubuntu/analytics/worker/Dockerfile, dockerfiles/ubuntu/integrator/Dockerfile
=> [6.5.x] Modify Dockerfiles to use base OS image and build Temurin OpenJDK 8 

dockerfiles/alpine/analytics/dashboard/Dockerfile, dockerfiles/alpine/analytics/worker/Dockerfile, dockerfiles/alpine/integrator/Dockerfile, dockerfiles/centos/analytics/dashboard/Dockerfile, dockerfiles/centos/analytics/worker/Dockerfile, dockerfiles/centos/integrator/Dockerfile, dockerfiles/ubuntu/analytics/dashboard/Dockerfile, dockerfiles/ubuntu/analytics/worker/Dockerfile, dockerfiles/ubuntu/integrator/Dockerfile
=> [6.6.x] Modify Dockerfiles to use base OS image and build Temurin OpenJDK 11

dockerfiles/alpine/mi-dashboard/Dockerfile, dockerfiles/alpine/micro-integrator/Dockerfile, dockerfiles/alpine/streaming-integrator/Dockerfile, dockerfiles/centos/mi-dashboard/Dockerfile, dockerfiles/centos/micro-integrator/Dockerfile, dockerfiles/centos/streaming-integrator/Dockerfile, dockerfiles/ubuntu/mi-dashboard/Dockerfile, dockerfiles/ubuntu/micro-integrator/Dockerfile, dockerfiles/ubuntu/streaming-integrator/Dockerfile
> To have more flexibility over the underline base OS image.
=> Modified Dockerfiles to use base OS image and build Temurin OpenJDKs

dockerfiles/alpine/micro-integrator/Dockerfile, dockerfiles/centos/micro-integrator/Dockerfile, dockerfiles/ubuntu/micro-integrator/Dockerfile
This PR will upgrade the JDK version from 11.0.20+8 to 11.0.21+9
Fixes issue: https://github.com/wso2/micro-integrator/issues/3040
=> [MI 4.1.0] Upgrading the JDK version

dockerfiles/alpine/micro-integrator/Dockerfile
> Upgrade release tag for MI 4.2.0 that introduce a version upgrade on alpine image..
=> [MI-4.2.0] Upgrade release tag for MI 4.2.0

dockerfiles/alpine/micro-integrator/Dockerfile
> To upgrade release tag for MI 4.1.0 that introduce a version upgrade on alpine image. 
related to https://github.com/wso2-enterprise/wso2-mi-internal/issues/303.
=> [MI-4.1.0] Upgrade release tag for MI 4.1.0

docker_image_release_process.md
> To introduce the set of guidelines which needed to be followed when releasing a docker image for a product.
=> [Docker] Add docker image release guidelines

dockerfiles/alpine/micro-integrator/Dockerfile, dockerfiles/centos/micro-integrator/Dockerfile, dockerfiles/ubuntu/micro-integrator/Dockerfile
> To obtain continuous updates in docker builds for base OS.
Related to MI Internal : https://github.com/wso2-enterprise/wso2-mi-internal/issues/337
=> [MI-4.2.0] Update centos dockerfile to get continuous updates

dockerfiles/alpine/streaming-integrator/Dockerfile
This PR upgrades the alpine version to 3.19.0 of SI image.
Related issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/5226
=> Upgrade SI image alpine version to 3.19.0

CHANGELOG.md, dockerfiles/alpine/mi-dashboard/Dockerfile, dockerfiles/alpine/micro-integrator/Dockerfile, dockerfiles/alpine/streaming-integrator/Dockerfile, dockerfiles/centos/mi-dashboard/Dockerfile, dockerfiles/centos/micro-integrator/Dockerfile, dockerfiles/centos/streaming-integrator/Dockerfile, dockerfiles/ubuntu/mi-dashboard/Dockerfile, dockerfiles/ubuntu/micro-integrator/Dockerfile, dockerfiles/ubuntu/streaming-integrator/Dockerfile
> This PR updates the ubuntu dockerfiles of MI dashboard and SI to get continuous upgrades and updates the required maintainer label of all docker files.
ports https://github.com/wso2/docker-ei/pull/337
=> [4.1.x] Update ubuntu dockerfiles to get continuous upgrades (Dashboard & SI)

CHANGELOG.md, dockerfiles/alpine/mi-dashboard/Dockerfile, dockerfiles/alpine/micro-integrator/Dockerfile, dockerfiles/alpine/streaming-integrator/Dockerfile, dockerfiles/centos/mi-dashboard/Dockerfile, dockerfiles/centos/micro-integrator/Dockerfile, dockerfiles/centos/streaming-integrator/Dockerfile, dockerfiles/ubuntu/mi-dashboard/Dockerfile, dockerfiles/ubuntu/micro-integrator/Dockerfile, dockerfiles/ubuntu/streaming-integrator/Dockerfile
> This PR updates the ubuntu dockerfiles of MI dashboard and SI to get continuous upgrades and updates the required maintainer label of all docker files.
Ports https://github.com/wso2/docker-ei/pull/337
=> [4.0.x] Update ubuntu dockerfiles to get continuous upgrades (Dashboard & SI)

dockerfiles/alpine/micro-integrator/Dockerfile, dockerfiles/rocky/micro-integrator/Dockerfile, dockerfiles/ubuntu/micro-integrator/Dockerfile
Update JDK version of micro integrator to `jdk-17.0.16+8`
=> Update JDK version of MI 4.2.0
